# Site settings

#google_analytics: UA-NNNNNNNN-N

title: Where is James Ray ?
author: Rémi Debord
email: remidebord@hotmail.fr

header_pages:
  - index.md
  - biography.md
  - songs.md
  - photos.md
  - references.md
  - about.md

footer: 'follow us on <a href="https://www.youtube.com/channel/UCf2aiQn8DLene52B7hz0tzA/videos">Youtube</a> and <a href="https://twitter.com/">twitter</a>'

style: light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
